---

- name: Install Shorewall
  apt:
    name: "{{ item }}"
  with_items:
    - shorewall
    - shorewall-doc

- name: Set Shorewall to run
  lineinfile:
    dest: /etc/default/shorewall
    line: 'startup=1'
    regexp: '^#?startup='
  notify:
    - Restart Shorewall

- name: Start with basic Shorewall configuration
  shell: 'cp -a /usr/share/doc/shorewall/examples/one-interface/* /etc/shorewall/ && gunzip -f *.gz'
  args:
    chdir: /etc/shorewall
    creates: /etc/shorewall/rules
  notify:
    - Restart Shorewall

- name: Enable Shorewall startup
  lineinfile:
    dest: /etc/shorewall/shorewall.conf
    line: 'STARTUP_ENABLED=Yes'
    regexp: '^#?STARTUP_ENABLED='
  notify:
    - Restart Shorewall

- name: Set Shorewall log file
  lineinfile:
    dest: /etc/shorewall/shorewall.conf
    line: 'LOGFILE=/var/log/shorewall.log'
    regexp: '^#?LOGFILE='
  notify:
    - Restart Shorewall

- name: Set Shorewall log rate limits
  lineinfile:
    dest: /etc/shorewall/shorewall.conf
    line: 'LOGLIMIT="10/minute:5"'
    regexp: '^#?LOGLIMIT='
  when: (ansible_distribution == "Debian" and ansible_distribution_major_version >= "9")
  notify:
    - Restart Shorewall

- name: Create Shorewall log file
  file:
    name: /var/log/shorewall.log
    state: touch
  notify:
    - Restart Shorewall
