---

# Backports includes (newer versions of) Ansible, letsencrypt, Docker, sysdig, tmux, Nginx, HAProxy, tcpdump, tshark, etc.
- name: Add Jessie backports Apt repo
  copy:
    src: files/etc/apt/sources.list.d/jessie-backports.list
    dest: /etc/apt/sources.list.d/jessie-backports.list

- name: Update apt
  apt:
    update_cache: yes

- name: Update all installed packages (that don't require any package removals)
  apt:
    upgrade: safe

# Apticron will send an email every day, if there are package updates to install.
# NOTE: This installs exim4, which we'll need to uninstall before installing Postfix.
- name: Install apticron
  apt:
    name: apticron
