---

# Certbot is EFF's official Let's Encrypt client.
- name: Install Certbot
  apt:
    name: certbot
    default_release: "{{ ansible_distribution_release }}-backports" # Don't really need backports for Debian 9 (Stretch)

# This will take several minutes on an x86_64 server; several hours on a Raspberry Pi.
- name: Generate a 4096-bit Diffie-Hillman key
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096
  args:
    creates: /etc/ssl/certs/dhparam.pem

- name: Enable Certbot renewal of Let's Encrypt certificates
  systemd:
    name: certbot.timer
    state: started
    enabled: TRUE
    daemon_reload: TRUE
    masked: FALSE

- name: Ensure Nginx is reloaded after certbot renews TLS certificates
  lineinfile:
    dest: /lib/systemd/system/certbot.service
    line: ExecStart=/usr/bin/certbot -q renew --renew-hook '/usr/sbin/nginx -s reload'
    regexp: '^ExecStart='
