---

- name: Install Nginx
  apt:
    name: "{{ item }}"
    default_release: "{{ ansible_distribution_release }}-backports"
  with_items:
    - nginx
    - nginx-doc
  notify:
    - Reload Nginx

- name: Set firewall rule for HTTP and HTTPS
  lineinfile:
    dest: /etc/shorewall/rules
    line: "ACCEPT net $FW tcp {{ item }}"
  with_items:
    - 80
    - 443
  notify:
    - Restart Shorewall

# Copy some settings from Debian's Nginx configuration.
- name: Configure Nginx defaults
  copy:
    src: files/etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - Check Nginx configuration
    - Reload Nginx

- name: Create Nginx configuration directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled
    - /etc/nginx/snippets

- name: Configure Nginx
  copy:
    src: files/etc/nginx/conf.d/
    dest: /etc/nginx/conf.d/
  notify:
    - Check Nginx configuration
    - Reload Nginx

- name: Include Nginx snippets
  copy:
    src: files/etc/nginx/snippets/
    dest: /etc/nginx/snippets/
  notify:
    - Check Nginx configuration
    - Reload Nginx

- name: Ensure Nginx starts on reboot
  systemd:
    name: nginx
    enabled: TRUE
    masked: FALSE
