---

- name: Install Nginx
  apt:
    name: "{{ item }}"
    default_release: jessie-backports
  with_items:
    - nginx
    - nginx-doc
  notify:
    - Reload Nginx

- name: Install Let's Encrypt and certbot
  apt:
    name: "{{ item }}"
    default_release: jessie-backports
  with_items:
    - letsencrypt
    - certbot
    - python-certbot-doc
    - python-acme-doc

- name: Set firewall rule for HTTP and HTTPS
  lineinfile:
    dest: /etc/shorewall/rules
    line: "ACCEPT net $FW tcp {{ item }}"
  with_items:
    - 80
    - 443
  notify:
    - Restart Shorewall

# This will take several minutes on an x86_64 server; several hours on a Raspberry Pi.
- name: Generate a 4096-bit Diffie-Hillman key
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096
  args:
    creates: /etc/ssl/certs/dhparam.pem

# Copy some settings from Debian's Nginx configuration.
- name: Configure Nginx defaults
  copy:
    src: files/etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - Check Nginx configuration
    - Reload Nginx

- name: Create Nginx configuration directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled
    - /etc/nginx/snippets

- name: Configure Nginx
  copy:
    src: files/etc/nginx/conf.d/
    dest: /etc/nginx/conf.d/
  notify:
    - Check Nginx configuration
    - Reload Nginx

- name: Include Nginx snippets
  copy:
    src: files/etc/nginx/snippets/
    dest: /etc/nginx/snippets/
  notify:
    - Check Nginx configuration
    - Reload Nginx

- name: Create TLS certificates via Let's Encrypt and certbot
  command: certbot certonly -n --agree-tos --email 'craig@boochtek.com' --keep --webroot -w /var/www/{{ item.site }}/public -d {{ item.domains }} --renew-hook 'systemctl reload nginx'
  args:
    creates: /etc/letsencrypt/live/{{ item.site }}/cert.pem
  with_items:
    - { site: www.boochtek.com, domains: "www.boochtek.com,boochtek.com" }

- name: Ensure Nginx is reloaded after Let's Encrypt certbot renews TLS certificates
  lineinfile:
    dest: /lib/systemd/system/certbot.service
    line: ExecStartPost=/usr/sbin/nginx -s reload
    insertafter: '^ExecStart='

- name: Enable Let's Encrypt via certbot
  systemd:
    name: certbot.timer
    state: started
    enabled: TRUE
    daemon_reload: TRUE
    masked: FALSE

- name: Ensure Nginx starts on reboot
  systemd:
    name: nginx
    enabled: TRUE
    masked: FALSE
