---

- name: Install Nginx
  apt:
    name: "{{ item }}"
    default_release: jessie-backports
  with_items:
    - nginx
    - nginx-doc

- name: Set firewall rule for HTTP and HTTPS
  lineinfile:
    dest: /etc/shorewall/rules
    line: "ACCEPT net $FW tcp {{ item }}"
  with_items:
    - 80
    - 443
  notify:
    - Restart Shorewall

- name: Configure Nginx
  copy:
    src: files/etc/nginx/conf.d/
    dest: /etc/nginx/conf.d/
  notify:
    - Check Nginx configuation
    - Reload Nginx
