---

- name: Update Apt cache
  apt:
    update_cache: yes

- name: Check Nginx configuration
  command: nginx -t
  notify:
    - Reload Nginx

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
    enabled: yes
